version: '2.3'
services:

  netdata:
    restart: always
    image: titpetric/netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    ports:
      - "127.0.0.1:19999:19999"
    volumes:
      - ./.docker/netdata:/etc/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - external_network

  mstdb:
    restart: always
    image: postgres:9.6-alpine
    networks:
      - mstdb_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./.docker/mastodon/db:/var/lib/postgresql/data

  mstredis:
    restart: always
    image: redis:alpine
    networks:
      - mstredis_network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./.docker/mastodon/redis:/data

#  mstes:
#    restart: always
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
#    environment:
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    networks:
#      - mstes_network
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#      - ./.docker/mastodon/es:/usr/share/elasticsearch/data

  mstweb:
    image: pluralcafe/mastodon:stable
    restart: always
    env_file: ./.docker/mastodon/.env.production
    networks:
      - external_network
      - mstdb_network
      - mstredis_network
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:4000:4000"
    depends_on:
      - mstdb
      - mstredis
#      - mstes
    volumes:
      - ./public/system:/mastodon/public/system
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

networks:
  external_network:
  mstdb_network:
    internal: true
  mstredis_network:
    internal: true
